# Generated by Django 3.1.3 on 2024-08-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=8)),
                ('major1', models.CharField(blank=True, max_length=20, null=True)),
                ('major2', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.IntegerField()),
                ('age', models.IntegerField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('blog_url', models.URLField(blank=True, null=True)),
                ('sns_url', models.URLField(blank=True, null=True)),
                ('club', models.TextField(blank=True, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('contest1', models.TextField(blank=True, null=True)),
                ('contest2', models.TextField(blank=True, null=True)),
                ('contest3', models.TextField(blank=True, null=True)),
                ('location', models.IntegerField()),
                ('intern', models.TextField(blank=True, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=36.5)),
                ('intro', models.TextField(blank=True, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='image_users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
