# Generated by Django 3.1.3 on 2024-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.DecimalField(decimal_places=1, default=36.5, max_digits=3),
        ),
    ]
