# Generated by Django 3.1.3 on 2024-08-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240820_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
