# Generated by Django 3.1.3 on 2024-08-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240823_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contest1',
            new_name='contest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contest2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contest3',
        ),
    ]
