# Generated by Django 3.1.3 on 2024-08-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='Recruitment')),
                ('linkareer', models.URLField()),
                ('category', models.IntegerField(default=9999)),
                ('ing', models.BooleanField()),
                ('num_people', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=100)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('team_name', models.IntegerField(default=1)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.question')),
            ],
        ),
    ]
