# Generated by Django 3.1.3 on 2024-08-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default=1, upload_to='image_recruitment'),
            preserve_default=False,
        ),
    ]
