# Generated by Django 3.1.3 on 2024-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0003_auto_20240818_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default=1, upload_to='image_recruitment'),
            preserve_default=False,
        ),
    ]
