# Generated by Django 3.1.3 on 2024-08-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0008_auto_20240818_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ing',
        ),
    ]
