# Generated by Django 3.1.3 on 2024-08-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0009_remove_question_ing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
