# Generated by Django 3.1.3 on 2024-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0012_auto_20240823_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='isteam',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
