# Generated by Django 3.1.3 on 2024-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0013_auto_20240823_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='isteam',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
